INSERT INTO carcenter.vehiculos (PLACA, COLOR, COD_MARCA, CLI_DOCUMENTO, CLI_TIPO_DOCUMENTO) VALUES ('BB3DDC', 'PLATA', 5, 102158546, 'C');
INSERT INTO carcenter.vehiculos (PLACA, COLOR, COD_MARCA, CLI_DOCUMENTO, CLI_TIPO_DOCUMENTO) VALUES ('FBR56R', 'AZUL', 1, 1024509779, 'C');
INSERT INTO carcenter.vehiculos (PLACA, COLOR, COD_MARCA, CLI_DOCUMENTO, CLI_TIPO_DOCUMENTO) VALUES ('FDB25D', 'BLANCO', 2, 103205348, 'C');
INSERT INTO carcenter.vehiculos (PLACA, COLOR, COD_MARCA, CLI_DOCUMENTO, CLI_TIPO_DOCUMENTO) VALUES ('JUF65V', 'VERDE', 2, 102158546, 'C');
INSERT INTO carcenter.vehiculos (PLACA, COLOR, COD_MARCA, CLI_DOCUMENTO, CLI_TIPO_DOCUMENTO) VALUES ('OMR89R', 'ROJO', 5, 103205348, 'C');
INSERT INTO carcenter.vehiculos (PLACA, COLOR, COD_MARCA, CLI_DOCUMENTO, CLI_TIPO_DOCUMENTO) VALUES ('OOD33C', 'NEGRO', 1, 1024509779, 'C');