INSERT INTO carcenter.servicios (CODIGO, NOMBRE_SERVICIO, PRECIO) VALUES (1, 'LAVAR', 12000);
INSERT INTO carcenter.servicios (CODIGO, NOMBRE_SERVICIO, PRECIO) VALUES (2, 'POLICHAR', 50000);
INSERT INTO carcenter.servicios (CODIGO, NOMBRE_SERVICIO, PRECIO) VALUES (3, 'REPARAR', 25000);
INSERT INTO carcenter.servicios (CODIGO, NOMBRE_SERVICIO, PRECIO) VALUES (4, 'CAMBIO ACEITE', 45122);
INSERT INTO carcenter.servicios (CODIGO, NOMBRE_SERVICIO, PRECIO) VALUES (5, 'DESPINCHAR', 12000);
INSERT INTO carcenter.servicios (CODIGO, NOMBRE_SERVICIO, PRECIO) VALUES (6, 'BRILLAR', 7800);